### PR TITLE
Time fixes

### PR DESCRIPTION
**Pull request by RhodiumToad**
See issue #336.

### CODE REVIEW

**Comment by RhodiumToad** [comment]
I hope you're not waiting for me to do anything about those coverage checks, because the changes look spurious.

**Comment by gvvaughan** [comment]
Nope... I'm waiting for myself to do something about luke checks using the wrong flags, and to improve debug logging...

**Comment by RhodiumToad** [comment]
poke

**Comment by gvvaughan** [comment]
Still at the top of my TODO - so little time!

**Comment by RhodiumToad** [comment]
poke

**Comment by gvvaughan** [comment]
Sorry for the delay.  I'm planning a new release in the next few days, finally, so merging this into a local branch to work on test failures with feedback from github actions CI.

**Comment by gvvaughan** [comment]
Gee, thanks GitHub.  This was merged, but from a temporary branch I made to run it through github actions.

**Pull request closed without merging**
