### PR TITLE
sys.socket: add getsockopt.

### PR DESCRIPTION
**Pull request by CMB**

### CODE REVIEW

**Comment by CMB** [comment]
I have one problem with this pull request.
My getsockopt wrapper either returns the value of the socket option,
or (nil, errstring, errnum).  But here's what the Linux manpage
has to say about getsockopt:

On success, zero is returned for the standard options.
On error, -1 is returned, and errno is set appropriately.
Netfilter allows the programmer to define custom socket options with associated
handlers; for such options, the return value on success is the value returned
by the handler.

So my implementation will discard those custom return values.
Apparently they're a quirk of Linux anyway.
I'm not sure whether that's a good idea, even though it does make life
simpler.  I could change it to return the two values
(return value, socket option value) in the success case, if
that is wanted.

**Comment by gvvaughan** [comment]
This matches the style we have for everything else wrapped by luaposix; your patch looks great to me.

If you would prefer to support linux quirks without breaking usage on other unices, that's not without precedent, and entirely your prerogative as the fine author of the pull request - and I'll wait for you to make the changes if you want. But IMHO, a premature optimization that can wait until someone actually wants to write linux specific code with luaposix.

**Comment by CMB** [comment]
Let's just go with the PR in its current form, then, and forget about
the Linux quirks for now.  Thanks!

**Comment by gvvaughan** [comment]
Awesome, thanks for the patches.  Merged :)

**Pull request merged**
