### PR TITLE
unistd: accept optional nbytes and buf_offset arguments to write.

### PR DESCRIPTION
**Pull request by parke**
* ext/posix/unistd.c (Pwrite): Accept an optional third nbytes parameter, and an optional fourth buf_offset_parameter.  Perform bounds checking.
* spec/posix_spec.yaml (write): Update specification.
* NEWS.md (New features): Update.

### CODE REVIEW

**Comment by parke** [comment]
Upon reflection, this line could be improved:  
`nbytes -= buf_offset;`

It would be clearer as:  
`nbytes = buf_len - buf_offset;`

I will try to add a second commit to this pull request.

**Comment by parke** [comment]
[gvvaughan wrote](https://github.com/luaposix/luaposix/issues/350#issuecomment-1376478567):
> Thought about this some more, and actually there's no need to co-opt `ERANGE` or whatever here, better to declare our own `EOOB` or whatever, make its value a negative integer so that it can never clash with anything exported by posix.errno, and then plumb it through `strerror` for completeness!

If you call `write ( 1, "hello", -1 )` on Linux, it sets `errno` to `EFAULT`.  The Linux man page describes the error as: "EFAULT buf is outside your accessible address space."  (Perhaps -1 converts to a maximal unsigned value?)  I believe the error string was "Bad address".

There is also `EINVAL` or `EDOM` ("Mathematics argument out of domain of function").

I have no preference as to which `errno` is used.

> There's also an opportunity to return a much better error dynamic string along the lines of "offset 25 is out of bounds in 8 byte string 'foobar'" from a failed `posix.unistd.write` call because we're not constrained by the static `errno` table when performing our own inline boundary checks.

Please feel free to add to my pull request as you see fit.

**Comment by gvvaughan** [comment]
Merged and tweaked a little for nicer diagnostics and to add spec examples for the new functionality.

I'll just need to check there are no outstanding PRs for easy bug fixes, and then I'll make a new release to luarocks.

Thank you for working on this PR!

**Comment by parke** [comment]
I see that you changed the name from `buf_offset` to `offset`.  This might cause confusion if `pwrite()` is ever added to `posix.unistd`, because `pwrite()` has a parameter named `offset` that is the offset in the file, not the offset in the buffer.  Just fyi.

**Comment by parke** [comment]
Regarding:  
`lua_pushfstring(L, "nbytes argument '%d' out of bounds for %d-byte buffer", nbytes, buf_len)`

If `buf_len == 20` and `offset == 15` and `nbytes == 10`, then you would get the error:

`nbytes argument '10' out of bounds for 20-byte buffer`

Whether or not this is a problem is up to you.

One alternative might be:

`offset+nbytes arguments of 15+10 out of bounds for 20-byte buffer`

**Comment by gvvaughan** [comment]
> I see that you changed the name from `buf_offset` to `offset`.

I prefer to follow the parameter names from the POSIX spec where possible.  If anyone ever submits a PR to bind `pwrite`, we can always clarify in the LDocs :-)

> If buf_len == 20 and offset == 15 and nbytes == 10, then you would get the error:
> 
>     nbytes argument '10' out of bounds for 20-byte buffer

Having slept on it, I'm thinking of changing both errors to:

    lua_pushfstring(L, "out of bounds access for %d-byte buffer '%.10s%s", buf_len, buf, buf_len > 10 ? "..." : "")

and reusing `EFAULT` as you suggested instead of my custom `PEOOB` error, for simplicity's sake.

**Comment by parke** [comment]
> ```
> lua_pushfstring(L, "out of bounds access for %d-byte buffer '%.10s%s'", buf_len, buf, buf_len > 10 ? "..." : "")
> ```

I recommend against including any portion of `buf` in the error message.

If you do include `buf`, remember that `buf` may contain arbitrary binary data, so you may need to transform it into safe bytes before displaying it.  For example, `buf` could contain terminal escape sequences.

Maybe: `invalid attempt to access offset %d in a buffer of length %d`

> and reusing `EFAULT` as you suggested instead of my custom `PEOOB` error, for simplicity's sake.

My first choice would be `EINVAL`, I think.

**Comment by gvvaughan** [comment]
All very true.  Thanks for saving me from myself there! https://github.com/luaposix/luaposix/commit/5f949f689b45339acc68c72c6b19d1885c33c459

**Pull request merged**
