### PR TITLE
fcntl: add O_CLOEXEC constant

### PR DESCRIPTION
**Pull request by fabled**

### CODE REVIEW

**Comment by gvvaughan** [comment]
Thanks for the patch, but O_CLOEXEC is not a POSIX API. However, FD_CLOEXEC can be passed to fcntl() with the same effect according to http://pubs.opengroup.org/onlinepubs/009695399/basedefs/fcntl.h.html.

Would you like to submit a patch for that, along with a suitable specl check to ensure that it keeps working?

**Comment by fabled** [comment]
The link you gave refers to old POSIX Issue; please look at the newer one which contains O_CLOEXEC at:
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/fcntl.h.html
http://pubs.opengroup.org/onlinepubs/9699919799/functions/open.html

But yes, it'd make sense adding FD_CLOEXEC too.

**Comment by gvvaughan** [comment]
Oh, interesting!  I followed the links from the luaposix LDocs to get to that old fcntl.h page... seems like I need to update the generator to use the newer URLs for everything.  Thanks :)

Two issues remain before I merge a pull-request:

1. Please provide a suitable specl check to ensure the feature works as advertised, and that we don't accidentally break it with future refactorings.
2. I'd prefer to avoid #ifdefs when possible, so either O_CLOEXEC is well enough supported that we should remove the #ifdef before merging... or if that is not sufficiently portable, better to bind FD_CLOEXEC in C, and then write an open() implementation in Lua that uses that to provide a Lua side fcntl.O_CLOEXEC implementation that works even when the C library doesn't provide a definition.

Cheers,
Gary

**Comment by fabled** [comment]
Maybe the unit test would be to open with O_CLOEXEC and then test for FD_CLOEXEC using getflags. So FD_CLOEXEC should probably be added at same time.

Regarding the second point. All modern C-libraries provide O_CLOEXEC, and emulate it with open+fcntl if running on old kernel. The question is what is the minimum C-library requirement. I'm happy to just remove the #ifdef if it is acceptable, I only added them because this is recent addition in the latest POSIX specification. Though, most OSes have supported it as extension long time before being standardized.

**Comment by gvvaughan** [comment]
ideally we'd like to support even minimal posixy libc implementations, and split the support into POSIX.2008, POSIX.2001, and pre-2001.

Having thought about this some more, Opengroup docs suggest that O_CLOEXEC is POSIX.2008, so worst case we could change your definition to be wrapped in `#ifdef LPOSIX_2008_COMPLIANT`, and predicate the specl check on a non-nil O_CLOEXEC value; but if you'd like to submit a gold-standard pull request, I'd love to see the O_CLOEXEC and open implementation all in just posix.lua over just a definition for FD_CLOEXEC in fcntl.c that we can rely on even with substandard mini-libc implementations :-)

**Comment by fabled** [comment]
Yes, it's new in POSIX.2008. Just checking O_CLOEXEC for non-nil sounds good test.

But I'd prefer to not try to emulate it always. In fact, it goes wrong if it's multithreaded program running lua in one thread (the other thread can fork, and you have race condition with the fd being inherited) -- this is the main reason it was added as argument to pretty much all syscalls; in some cases even adding new syscall variant.

**Comment by fabled** [comment]
Perhaps you could rework the patch to be something acceptable. I'm not quite sure how to do the specl check.

Btw. another reason for using O_CLOEXEC directly is performance. It avoids a syscall which usually is costly in cpu time sense.

**Comment by gvvaughan** [comment]
Okay.  I'll add it to my TODO list, but it might be a while before I get to it. If you tire of waiting, please go ahead and resubmit.

**Comment by gvvaughan** [comment]
Having given this some more though, and especially considering that we're trying to make luaposix a much thinner binding over the system POSIX APIs I took your patch with just a few tweaks:

- define O_CLOEXEC to 0 on systems without a definition so that it doesn't break bitwise OR
- also define FD_CLOEXEC so the caller can fallback to it when appropriate, and be aware that the system didn't quietly emulate O_CLOEXEC non-atomically
- tweaked the comments, commit message and added a NEWS entry

Thanks!

**Pull request closed without merging**
