### PR TITLE
build: remove posix.bit32

### LINKED ISSUE #204: Use bit32 rock for 5.1 rather than reproduce it in luaposix
There's a backport of the bit32 library to Lua 5.1 available as a rock, so use that instead of reimplementing it.

### PR DESCRIPTION
**Pull request by rrthomas**
Close #204 again, removing posix.bit32 in favour of a rockspec
dependency, which will use the built-in library in Lua >= 5.2, or the
backported rock in Lua 5.1

### CODE REVIEW

**Comment by rrthomas** [comment]
The failure on Lua 5.3 I can't immediately trace to this change. Ideas, @gvvaughan? The failure on LuaJIT is down to bit32 not working there (but it has luabitop); I shall cogitate…

**Comment by gvvaughan** [comment]
That's plain weird...  I checked out your branch in my lua53 container, and it builds and passes make check just fine.  Maybe restart the failed build on Travis to see whether it was just a solar flare that flipped some bits randomly?

That said, if we have to choose between luabitop and bit32 at configure-time, the cure seems worse than the disease... :-(

**Comment by rrthomas** [comment]
I'm somewhat hampered by LuaRocks's documentation site having (temporarily, I assume) vanished (yes, I've notified the authorities), but as far as I can tell alternative dependencies have not yet been implemented, which means I should fix the bit32 backport so that it also compiles against LuaJIT. I see this is from Hisham's lua-compat-5.2 project.

**Comment by gvvaughan** [comment]
Good idea!

I believe the LuaRocks wiki is being converted to Lapis where a mirror will be served from moonscript.org shortly...

**Comment by rrthomas** [comment]
Nope, the 5.3 build failure wasn't a Heisenbug, sorry.

**Comment by gvvaughan** [comment]
When Travis decides to go nuts like this, I tend to make a `debug-travis-failure` branch or similar, and start committing changes to .travis.yml that turn up the verbosity until I can figure out what is going on... I think travis is running Ubuntu 10.04, whereas my containers are on 12.04 which might account for the slight difference of opinion about whether `remove-builtin-bit32` is working...

**Comment by rrthomas** [comment]
I'll have to leave Travis/5.3 for the morning, but for the record "Travis CI virtual machines are based on Ubuntu 12.04 LTS Server Edition 64 bit".

**Comment by gvvaughan** [comment]
Thanks... even so, they still go awry for no obvious reason from time to time! Bah :-?

**Comment by rrthomas** [comment]
The `bit32` rock already had unreleased changes that made it build with LuaJIT; I merely updated it to 5.2.3, as that had a small code fix. Hence, now waiting on keplerproject/lua-compat-5.2#18

**Comment by rrthomas** [comment]
As far as the Lua 5.3 errors go, is Travis building with sufficiently up-to-date versions of the build-deps?

**Comment by gvvaughan** [comment]
Well, it builds Lua and luarocks from source, and then pulls rocks from the gvvaughan manifest at moonrocks (because I needed a Lua 5.3 LFS for LDocs) falling back to the root manifest. Everything is in the Travis log though, so it's easy enough to compare to your local environment's versions...

**Comment by siffiejoe** [comment]
FYI, the documentation from the previous luarocks site has found a temporary home in the [github wiki][1]. (I don't know how much has been converted already.)

  [1]: https://github.com/keplerproject/luarocks/wiki

**Comment by rrthomas** [comment]
Thanks @sifflejoe.

**Comment by rrthomas** [comment]
@gvvaughan I installed stdlib 41.0.0 and indeed `make check` passes with Lua 5.3.

**Comment by rrthomas** [comment]
My update to `bit32` has been applied, so we're just waiting for the new 5.2.3 rock on that part of the issue.

**Comment by rrthomas** [comment]
Sorry, I was confusing specl 14.1.0 and stdlib 41.0.0; luaposix doesn't use stdlib.

**Comment by rrthomas** [comment]
OK, when I actually check out the right branch and build with 5.3, I can repro the failure from Travis, so I think I should be able to find it now.

**Comment by rrthomas** [comment]
It's because it can't find `bit32` in Lua 5.3.

**Comment by rrthomas** [comment]
(It's annoying that this error is not propagated.)

**Comment by rrthomas** [comment]
It seems a change to luarocks is needed not to assume `bit32` is present in Lua 5.3, and I need to make the rock installable in 5.3.

**Comment by siffiejoe** [comment]
@rrtthomas: Removing `bit32` from the builtin modules in LuaRocks is easy. See keplerproject/luarocks#243. I'm not sure it should be done, though. What was wrong again with the `posix.bit32` approach?

**Comment by rrthomas** [comment]
`posix.bit32` is a per-project fix for something that should just work. It's a pain that Lua 5.1, 5.2 and 5.3 have respectively no bitops, bit32 and built-in operators; the simplest solution seems to be to provide `bit32` on all versions: that then works with any Lua installation for any project, simply by declaring the `bit32` dependency.

**Comment by rrthomas** [comment]
After further investigation, I realised my Lua 5.3 build is at fault here: I still had `LUA_COMPAT_ALL` copied from my 5.2 build patches, rather than `LUA_COMPAT_5_2`, so I don't need to change the default setting for `bit32` in luarocks.

**Comment by rrthomas** [comment]
This is now looking good @gvvaughan

**Comment by msva** [comment]
@rrthomas @gvvaughan 
so, since internal bit32 is removed, can you somehow describe buildprocess (without luarocks) against lua5.1 and luajit?
Which package should be considered as dependency then? https://github.com/ezdiy/lua-bit32 ? or do you have some own fork?

**Comment by rrthomas** [comment]
The dependency is on bit32. (See the luarock.)

**Comment by msva** [comment]
yes, dependency is on `bit32`. But that was a bit unclear that `bit32` "rock" dependency is a https://github.com/keplerproject/lua-compat-5.2 (I mean, far not all people using luarocks to install packages, so it will be very good to not be rocks-centric and provide some info about non-rocks compilation. Anyway, thanks, I'll try to package keplerproject compat library too and add it as dependency for 5.1 builds (lua51 and luajit2)

**Comment by rrthomas** [comment]
Not sure how this is unclear: the rockspec specifies the rock dependencies, and you can look up the rock to find the sources.

We're not supporting non-luarocks compilation. (But of course we aren't trying to make it hard!)

I don't understand the comment about 5.1 builds: luaposix already works on 5.1, or should.

**Comment by gvvaughan** [comment]
Before you can even get started, you will need to have all prerequisites installed:

 Automake, Autoconf, Libtool, GNU M4, Perl, Bourne Shell, Shell Utilities etc... this list is not exhaustive.

Note also that not all bootstrap Lua dependencies are listed in the rockspec -- because everyone else apart from me, Reuben and you use release tarballs or LuaRocks -- so you'll also need the ldoc stack and the specl stack, which also includes a released stdlib and a release luaposix.  If you know what you are doing, then you'll find a way to skip those last two in `bootstrap --help`, but then you won't be able to regenerate the documentation or run the tests.

You may choose to download the latest gnulib in a sibling directory to save hitting the network again at bootstrap time.

With all of that in place, from the top-level checked out source directory:

```bash
./bootstrap --gnulib-src=../newer-than-luaposix-github-workingdir-checkout
./configure --prefix=/staging-directory
make
# provided you didn't skip the specl checks, you can also:
make check V=1
sudo make install
```

I took a lot of time to make the bootstrap failure messages as informative as possible, so if it is unhappy at any point, it will stop and tell you why it is unhappy, and maybe what you should do before trying again.

Please note that there are full logs of bootstrapped builds on Linux on LuaJIT, and PUC Rio Lua 5.1, 5.2 and 5.3 on Travis.  If you can't figure out how to set your environment up to bootstrap luaposix, you can always pick the same checkout hash you are struggling with from those logs to see how our integration tests did it.

Bear in mind too, I am close to updating all the README.md files to explicitly state that if you are redistributing our Lua projects, or otherwise choosing to do a full low-level bootstrap build from scratch, we don't have the time to provide good support.  It is a difficult finicky process that involves deep knowledge of Autotools, Lua and setting up a couple of stacks that are quite time-consuming and fiddly in their own right if you are avoiding LuaRocks... if you don't have that knowledge, you would probably be better off using an already bootstrapped release tarball, or better yet managing your Lua packages with a Lua package manager.  Hope this doesn't seem too harsh - of course I want you to be able to use and enjoy luaposix and the other software I maintain in whatever capacity you choose, but I'd rather spend my time working on fixing bugs and adding features for everyone than teaching a few people how to do bootstrap builds with Autotools.

Cheers,
Gary

**Pull request merged**
