### PR TITLE
Popen

### PR DESCRIPTION
**Pull request by rrthomas**
This pull request adds `popen` and `popen_pipeline` which are based on the existing `pipeline` (and aim to obsolete it), fixing issue #81 (because stdout is no longer redirected in the current process) and reducing the number of processes needed for a pipeline from 2 per command to 1 (because we use the new `execx` directly from the child rather than `spawn`).

This also brings the API closer to the familiar `io.popen`, but with the two key advantages of `pipeline`, namely the process-launching-fu of `spawn` (now moved into `execx`), and the ability to specify a pipe creation function other than `pipe`.

My previous use of `pipeline` now uses `posix.popen` (and doesn't even need a pipeline, because where previously it had an extra process to gather the output of the command, it now reads the command's output directly). I would be happy to remove `pipeline` (the new code is more modular and shorter overall); otherwise we should deprecate it.

### CODE REVIEW

**Comment by gvvaughan** [comment]
Awesome, thank you! Merged again.

I cherry-picked 12f5a10 to avoid picking up e89a3e0 and 4280ec9 again, and tweaked the commit message to make for a nicer ChangeLog entry at release time.

**Comment by rrthomas** [comment]
What about the suggested deprecation of `pipeline`?

**Comment by gvvaughan** [comment]
It seems very likely that you are the only client of `pipeline`, and we didn't commit the Zile `pipeline` patch to master - it's likely that it wasn't even a documented API until the last release or two - so I don't think it would upset anyone if you want to remove it altogether.

The polite thing to do would be to deprecate it, but we don't have the stdlib deprecation machinery available in luaposix yet... I plan to make stdlib an optional dependency to enable argument type checks soon though, so you might want to bring that idea forward and provide a deprecation warning as well as removing the LDocs.

What would you prefer? I'm leaning toward simply removing it.

**Comment by rrthomas** [comment]
I'm very happy simply to remove it.

On 27 February 2015 at 14:29, Gary V. Vaughan <notifications@github.com>
wrote:

> It seems very likely that you are the only client of pipeline, and we
> didn't commit the Zile pipeline patch to master - it's likely that it
> wasn't even a documented API until the last release or two - so I don't
> think it would upset anyone if you want to remove it altogether.
>
> The polite thing to do would be to deprecate it, but we don't have the
> stdlib deprecation machinery available in luaposix yet... I plan to make
> stdlib an optional dependency to enable argument type checks soon though,
> so you might want to bring that idea forward and provide a deprecation
> warning as well as removing the LDocs.
>
> What would you prefer? I'm leaning toward simply removing it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luaposix/luaposix/pull/212#issuecomment-76402345>.
>



-- 
http://rrt.sc3d.org

**Pull request closed without merging**
