### PR TITLE
Added getsockname

### PR DESCRIPTION
**Pull request by zevv**

### CODE REVIEW

**Comment by gvvaughan** [comment]
Hi Zevv,

Looks good... I'll merge right away if you add an example and/or tests ;-)

Otherwise I'll get to it in a week or two when I'll have time to add tests myself.

Cheers,
Gary

**Comment by zevv** [comment]
Hi Gary,

* On 2015-02-11 15:10:39 +0100, Gary V. Vaughan wrote:
 
> Looks good... I'll merge right away if you add an example and/or tests ;-)
> Otherwise I'll get to it in a week or two when I'll have time to add tests myself.

I just added a simple invocation to examples/socket.lua. I still didn't
bother to setup the environment required to run slingshot and the test
tools, sorry for that.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by gvvaughan** [comment]
Hi Zevv,

Thanks for the extra binding!  I merged it and added a basic argument checking example to the spec file.

Please rebase to a more modern revision for future patches... you're 213 commits behind HEAD before I ported this change forward, so you're missing out on Lua 5.3 compatibility and quite a few fixes in the socket library to boot.

Getting Specl set up is super-easy:

```
$ luarocks install specl
$ # if you like colors: luarocks install ansicolor
$ cd luaposix--github--master
$ make check
```

Cheers!

**Comment by zevv** [comment]
* On 2015-02-11 17:56:31 +0100, Gary V. Vaughan wrote:
 
> Thanks for the extra binding!  I merged it and added a basic argument
> checking example to the spec file.
> 
> Please rebase to a more modern revision for future patches... you're
> 213 commits behind HEAD before I ported this change forward, so you're
> missing out on Lua 5.3 compatibility and quite a few fixes in the
> socket library to boot.

Ok, will do. 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Pull request merged**
