### PR TITLE
posix.lua: remove ability to pass a simple string to execx

### PR DESCRIPTION
**Pull request by rrthomas**

### CODE REVIEW

**Comment by rrthomas** [comment]
See #216 for the argument.

**Comment by rrthomas** [comment]
I suppose that in keeping with the argument of #216, if this PR is acceptable I should also remove the old `posix.system` alias?

**Comment by gvvaughan** [comment]
Hi Reuben,

On the one hand, please feel free to commit to master without the pull-request bureaucracy.

Otherwise, for cleaner merges (i.e. so I don't have to figure out which changesets to cherrypick), unless one pull request depends on another, please base each new pull-request from origin/master before submitting... otherwise if I merge in the wrong order I end up pulling in unrelated changesets in one pul-request (b47af57 in this case), and then (if I'm lucky) merge conflicts in the other changeset when I try to merge that one.

Review comments to follow... :)

Cheers,
Gary

**Comment by rrthomas** [comment]
About basing of PRs: recently, I had the fdopen commits in the popen PR, because originally I thought they would be required; they weren't, sorry. This time, I'm a bit confused: the unrelated commit is d94dfc0 (fix type-checking for popen, which I added because it would have avoided a bug in my original popen PR). Putting that in this PR was a bit lazy of me.

About removing the system alias for spawn: it's the _system alias_ I'm removing, not the spawn call, which remains necessary.

I think that answers all your questions. I preferred not to push directly in this case precisely because I thought you would have queries, as you did!

**Comment by gvvaughan** [comment]
Cherry picked as 3 separate commits, and edited log messages lightly before pushing.  Note that I didn't add the `M.popen` binding in d94dfco.

**Pull request closed without merging**
